name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: mkdir release|| go build -v ./... -o ./release/

    - name: Create a Release
#      if: ${{ env.RELEASE_VERSION != '' }}
      uses: elgohr/Github-Release-Action@main
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: "RELEASE"
