name: Go

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'version on release'
        required: false
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build-dirRenameCopy
        run: mkdir release||cd ./dirRenameCopy || go get || go build -o ../release/dirRenameCopy

      - name: Build-tagClassification
        run: mkdir release||cd ./tagClassification || go get || go build -o ../release/tagClassification

      - name: Create a Release
        if: ${{ github.event.inputs.releaseVersion != '' }}
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: "v0.0.2"
